server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_usuarios
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ms-usuarios
appDescription: "Pragma Powerup"
appVersion: "1.0.0"